version: "2.1"
services:
  smokeping:
    image: ghcr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - PGTZ=Europe/Prague
      - VIRTUAL_PORT=80
#      - LETSENCRYPT_TEST=true
      - VIRTUAL_HOST=smokeping.akira.cz
      - LETSENCRYPT_HOST=smokeping.akira.cz
      - LETSENCRYPT_EMAIL=hufhendr@gmail.com

    volumes:
      - "$PWD/config:/config"
      - "$PWD/data:/data"
    expose:
      - "80"

    restart: always

networks:
  default:
    external:
      name: prometheus
